### PR TITLE
Rewrote and commented dead code

### PR DESCRIPTION
**Pull request by dkempe**
I wrote a comment associated with these changes in the original repository. This pull request implements the changes I referenced.

### CODE REVIEW

**Comment by bennn** [comment]
This reminds me how the plot library needs continuous integration. I think I'll try adding that this weekend.

**Comment by stamourv** [comment]
If this is dead code, we should just delete it, not comment it out.
If we do need it later, we can find it in the git history.

**Comment by dkempe** [comment]
The problem with this approach is that the code is incorrect AND dead. If we just delete it and find that we need it later, we will revert to the code with out-of-scope vector references. I can submit two pull requests, one which fixes the code and one that deletes it, but they would need to be pulled in that order.

**Comment by stamourv** [comment]
That makes sense.
Pull requests can have multiple commits in the, so only one is necessary.
IIRC, you can also force-push to this branch to update this PR, so you don't even need to create a new one.
Thanks for looking into this!

**Comment by bennn** [comment]
Finally merged. Thanks again for working on this pull request.

87a0d2bf59cbc9458ae6ea874bdd24652fec4239
6ca968b43e4f7fa29a06942a13ca5516b45a4f33

**Pull request closed without merging**
