### PR TITLE
Provide plot2d interface unsafely to avoid excessive overhead

### PR DESCRIPTION
**Pull request by bennn**
https://github.com/racket/drracket/issues/185

cc @racket/release

### CODE REVIEW

**Comment by stamourv** [comment]
Do the arguments that made the change safe in the 3d case apply here too?

**Comment by bennn** [comment]
I think so, but I haven't looked carefully yet. Should I do that ASAP, or can it wait until later tonight?

**Comment by stamourv** [comment]
Later tonight is fine.

**Comment by jbclements** [comment]
Many thanks!

**Comment by bennn** [comment]
Yep, `plot-snip` `plot-frame` and `plot` appear safe to provide unsafely.

**Pull request merged**
