### PR TITLE
Fix _spec_ to match apply-jitter

### PR DESCRIPTION
**Pull request by bennn**
EDIT: docs now say that total deviation is 2x the amount given for `x-jitter` etc

### CODE REVIEW

**Comment by bennn** [comment]
Now the docs show:
screen shot 2016-04-26 at 06 03 31

**Comment by stamourv** [comment]
Does it make more sense to specify the jitter in terms of the size of the rectangle (as the docs did, but the implementation didn't), or in terms of the maximum deviation from the original value (the other way around). The latter feels more intuitive to me, but given that I only have a vague sense of what that feature is for, take that with a pinch of salt. :)

**Comment by bennn** [comment]
Either one is fine to me, but rectangle size seems easier to explain in the docs and less work to change in this PR.

**Comment by samth** [comment]
What do other libraries with this feature do?

**Comment by bennn** [comment]
R matches our implementation (not our docs) -- "total spread is twice the amount specified". I'll change this PR.
- http://docs.ggplot2.org/current/geom_jitter.html
- http://docs.ggplot2.org/current/position_jitter.html

**Comment by bennn** [comment]
@stamourv just fyi here's a recent case where this feature was useful

We were suspicious that running the same benchmarks on multiple cores was giving very different results from single core measurements, so we ran a few versions of a program (numbered 0 - 15 on the x-axis) 30 times both sequentially and in parallel. Each green dot is 1 run of 1 version; all green dots were run sequentially on a dedicated core. Red dots are 1 run of 1 version but each version is run in parallel. The y-axis has the absolute runtimes.

shuffle-4-exact


Applying jitter helps see the actual distribution of the running times. I like this much better than using a boxplot or violin plot.

**Comment by stamourv** [comment]
Given the new behavior, would it be better to have the docs written in terms of distance from the true value, as opposed to size of the rectangle?

**Comment by rfindler** [comment]
@bennn can you explain how you've used jitter to produce this plot?

**Comment by bennn** [comment]
@stamourv I don't like the `2*` factors, but I still think rectangles are the simplest, shortest way to explain what the parameters do. (Else idk, "e.g. `'(0 0)` is moved at most 1 unit along either axis" ?)

@rfindler the data had integer-valued x-coordinates: 60 points at x=0, 60 points at x=1, etc. I called `(points ... #:x-jitter 0.5)` to make it easier to see variations in the points' y-positions.

**Comment by rfindler** [comment]
The smallest y coordinate on the plot appears to be 500? I'm confused.

**Comment by bennn** [comment]
Yes, the y-coordinates seem to range between 400ms and 2000ms.

Here is the same plot without any jitter. Does this help the confusion?
ack

**Comment by rfindler** [comment]
Yes, completely. Thanks!

**Comment by stamourv** [comment]
@bennn: I don't have strong feelings either way re docs. Go with what you feel is best. LGTM otherwise.

**Comment by bennn** [comment]
(Ran it by 2 other people, took the rectangle out of `points3d`'s explanation. Thanks for the feedback!)

**Pull request merged**
