### PR TITLE
test: add a way to regenerate test data

### PR DESCRIPTION
**Pull request by sorawee**

### CODE REVIEW

**Comment by alex-hhh** [comment]
Not sure what you aim with this PR, but I wanted it to make it more difficult to quickly override images and draw steps for failed tests.

Currently, the developer has to stop and think and manually verify that each of the failing tests don't introduce actual visual problems with the plot.  With your proposed change it becomes too easy for a developer to simply decide "I'm sure my changes are OK, let me just update all these tests at once and go..."

**Comment by sorawee** [comment]
My two cents: 

They won't be able to "quickly override images and draw steps for failed tests", because there is a review process.

On the other hand, overriding the file allows one to compare images in GitHub diff view, which is much easier than finding two specific files from a directory with hundred files, and then arrange windows to compare them side by side.

To me, this is simply a convenience tool.

**Comment by alex-hhh** [comment]
I considered adding this feature when I originally implemented these tests but decided not to.  

Making it too convenient to update these tests introduces the risk of putting backwards incompatible changes in the plot package, where the output of the plot changes between releases (even if the API stays the same).

The current setup is not ideal, but it does not seem to prevent or hinder people from contributing features and fixes to the plot package (many contributions were done since I introduced this system several years ago).   If this becomes a practical problem in the future, I'll reconsider it.

---

> They won't be able to "quickly override images and draw steps for failed tests", because there is a review process.

The review process is not perfect and can fail too.  In my professional field, the systems we design have multi-layered safety features and one cannot justify removing safety features just because "there is at least one safety feature remaining."  

> On the other hand, overriding the file allows one to compare images in GitHub diff view, which is much easier than finding two specific files from a directory with hundred files, and then arrange windows to compare them side by side.

Comparing images is easy in Github, but as you noted yourself in #126 , images will never be identical, and it is easy to look at images, and decide that any changes on the image are caused by platform specific differences. 

The ".DAT" files, which contain the rendering steps, are the true indicator of what changed, and if a change is backwards compatible or not.  Unfortunately, these binary files cannot be diff-ed in Github, since they are compressed, to save in file size.

Making it "convenient" would make people rely on the Github image diff, which is the wrong thing to do.

**Comment by sorawee** [comment]
Thanks for the explanation!

**Pull request closed without merging**
