### PR TITLE
make CI build from the repository and not from the catalog

### PR DESCRIPTION
**Pull request by ralsei**
This likely also fixes the CI issue from #86 (...somehow). Looking through the logs of the CI build:
```
Resolved "plot" via file:///home/runner/work/plot/plot/catalog
00: Resolved "plot-lib" via file:///home/runner/work/plot/plot/catalog
00: Resolved "plot-gui-lib" via file:///home/runner/work/plot/plot/catalog
Resolved "plot-doc" via file:///home/runner/work/plot/plot/catalog
```

### CODE REVIEW

**Comment by ralsei** [comment]
And, for whatever reason, it's now pulling from the catalog. Wonderful...

**Comment by alex-hhh** [comment]
Looking at the build logs for the "Racket 8.0 CS", I see:

```
Resolving "plot" via https://download.racket-lang.org/releases/8.0/catalog/
Downloading https://download.racket-lang.org/releases/8.0/pkgs/plot.zip
00: Resolving "plot-lib" via https://download.racket-lang.org/releases/8.0/catalog/
01: Resolving "plot-gui-lib" via https://download.racket-lang.org/releases/8.0/catalog/
Resolving "plot-doc" via https://download.racket-lang.org/releases/8.0/catalog/
```

So this change still resolves plot via the catalog, instead of using the local checked out sources.

My guess is that the problem is caused by the fact that the catalog setup commands are run as a regular user (no sudo), while the build commands are run using "sudo", so they might pick up a different config location, for the root user.  I think this worked in an older version of setup-racket, and got "fixed" in newer versions, but I didn't notice  it.

I think the fix is to remove the "sudo" part from the build commands -- the build should work without them.  Can you please try that?  

Updating to 8.0 and to racket-setup 1.1. is also good, so please keep these changes in the pull request.

Thanks,
Alex.

**Comment by ralsei** [comment]
It looks like making it rootless was the trick.

**Comment by alex-hhh** [comment]
Thanks for trying this out and submitting a fix.

**Pull request merged**
